(function () {
  window.getResourceText = function () {
    return (
      '# *DO NOT DIRECTLY EDIT THIS FILE, IT IS AUTOMATICALLY GENERATED AND IT IS BASED ON:*\n' +
      '# https://docs.google.com/spreadsheet/ccc?key=0AmQEO36liL4FdDJLWVNMaVV2UmRKSnpXU09MYkdGbEE\n' +
      'aboutDrawio=About draw.io\n' +
      'accessDenied=Access Denied\n' +
      'action=Action\n' +
      'actualSize=Actual Size\n' +
      'add=Add\n' +
      'addedFile=Added {1}\n' +
      'addImages=Add Images\n' +
      'addImageUrl=Add Image URL\n' +
      'addLayer=Add Layer\n' +
      'addProperty=Add Property\n' +
      'address=Address\n' +
      'addToExistingDrawing=Add to Existing Drawing\n' +
      'addWaypoint=Add Waypoint\n' +
      'adjustTo=Adjust to\n' +
      'advanced=Advanced\n' +
      'align=Align\n' +
      'alignment=Alignment\n' +
      'allChangesLost=All changes will be lost!\n' +
      'allPages=All Pages\n' +
      'allProjects=All Projects\n' +
      'allSpaces=All Spaces\n' +
      'allTags=All Tags\n' +
      'anchor=Anchor\n' +
      'android=Android\n' +
      'angle=Angle\n' +
      'arc=Arc\n' +
      'areYouSure=Are you sure?\n' +
      'ensureDataSaved=Please ensure your data is saved before closing.\n' +
      'allChangesSaved=All changes saved\n' +
      'allChangesSavedInDrive=All changes saved in Drive\n' +
      'allowPopups=Allow pop-ups to avoid this dialog.\n' +
      'allowRelativeUrl=Allow relative URL\n' +
      'alreadyConnected=Nodes already connected\n' +
      'apply=Apply\n' +
      'archiMate21=ArchiMate 2.1\n' +
      'arrange=Arrange\n' +
      'arrow=Arrow\n' +
      'arrows=Arrows\n' +
      'asNew=As New\n' +
      'atlas=Atlas\n' +
      'author=Author\n' +
      'authorizationRequired=Authorization required\n' +
      'authorizeThisAppIn=Authorize this app in {1}:\n' +
      'authorize=Authorize\n' +
      'authorizing=Authorizing\n' +
      'automatic=Automatic\n' +
      'autosave=Autosave\n' +
      'autosize=Autosize\n' +
      'attachments=Attachments\n' +
      'aws=AWS\n' +
      'aws3d=AWS 3D\n' +
      'azure=Azure\n' +
      'back=Back\n' +
      'background=Background\n' +
      'backgroundColor=Background Color\n' +
      'backgroundImage=Background Image\n' +
      'basic=Basic\n' +
      'blankDrawing=Blank Drawing\n' +
      'blankDiagram=Blank Diagram\n' +
      'block=Block\n' +
      'blockquote=Blockquote\n' +
      'blog=Blog\n' +
      'bold=Bold\n' +
      'bootstrap=Bootstrap\n' +
      'border=Border\n' +
      'borderColor=Border Color\n' +
      'borderWidth=Borderwidth\n' +
      'bottom=Bottom\n' +
      'bottomAlign=Bottom Align\n' +
      'bottomLeft=Bottom Left\n' +
      'bottomRight=Bottom Right\n' +
      'bpmn=BPMN\n' +
      'browser=Browser\n' +
      'bulletedList=Bulleted List\n' +
      'business=Business\n' +
      'busy=Operation in progress\n' +
      'cabinets=Cabinets\n' +
      'cancel=Cancel\n' +
      'center=Center\n' +
      'cannotLoad=Load attempts failed. Please try again later.\n' +
      'cannotLogin=Log in attempts failed. Please try again later.\n' +
      'cannotOpenFile=Cannot open file\n' +
      'change=Change\n' +
      'changeOrientation=Change Orientation\n' +
      'changeUser=Change user\n' +
      'changeStorage=Change storage\n' +
      'changesNotSaved=Changes have not been saved\n' +
      'userJoined={1} has joined\n' +
      'userLeft={1} has left\n' +
      'chatWindowTitle=Chat\n' +
      'chooseAnOption=Choose an option\n' +
      'chromeApp=Chrome App\n' +
      'collaborativeEditingNotice=Important Notice for Collaborative Editing\n' +
      'compressed=Compressed\n' +
      'commitMessage=Commit Message\n' +
      'csv=CSV\n' +
      'dark=Dark\n' +
      'draftFound=A draft for \'{1}\' has been found. Load it into the editor or discard it to continue.\n' +
      'dragAndDropNotSupported=Drag and drop not supported for images. Would you like to import instead?\n' +
      'dropboxCharsNotAllowed=The following characters are not allowed: \ / : ? * " |\n' +
      'check=Check\n' +
      'checksum=Checksum\n' +
      'circle=Circle\n' +
      'cisco=Cisco\n' +
      'classic=Classic\n' +
      'clearDefaultStyle=Clear Default Style\n' +
      'clearWaypoints=Clear Waypoints\n' +
      'clipart=Clipart\n' +
      'close=Close\n' +
      'collaborator=Collaborator\n' +
      'collaborators=Collaborators\n' +
      'collapse=Collapse\n' +
      'collapseExpand=Collapse/Expand\n' +
      'collapse-expand=Click to collapse/expand\nShift-click to move neighbors \nAlt-click to protect group size\n' +
      'collapsible=Collapsible\n' +
      'comic=Comic\n' +
      'comment=Comment\n' +
      'commentsNotes=Comments/Notes\n' +
      'compress=Compress\n' +
      'connect=Connect\n' +
      'connecting=Connecting\n' +
      'connectWithDrive=Connect with Google Drive\n' +
      'connection=Connection\n' +
      'connectionArrows=Connection Arrows\n' +
      'connectionPoints=Connection Points\n' +
      'constrainProportions=Constrain Proportions\n' +
      'containsValidationErrors=Contains validation errors\n' +
      'copiedToClipboard=Copied to clipboard\n' +
      'copy=Copy\n' +
      'copyConnect=Copy on connect\n' +
      'copyCreated=A copy of the file was created.\n' +
      'copyOf=Copy of {1}\n' +
      'copyOfDrawing=Copy of Drawing\n' +
      'copySize=Copy Size\n' +
      'copyStyle=Copy Style\n' +
      'create=Create\n' +
      'createNewDiagram=Create New Diagram\n' +
      'createRevision=Create Revision\n' +
      'createShape=Create Shape\n' +
      'crop=Crop\n' +
      'curved=Curved\n' +
      'custom=Custom\n' +
      'current=Current\n' +
      'cut=Cut\n' +
      'dashed=Dashed\n' +
      'decideLater=Decide later\n' +
      'default=Default\n' +
      'delete=Delete\n' +
      'deleteColumn=Delete Column\n' +
      'deleteLibrary401=Insufficient permissions to delete this library\n' +
      'deleteLibrary404=Selected library could not be found\n' +
      'deleteLibrary500=Error deleting library\n' +
      'deleteLibraryConfirm=You are about to permanently delete this library. Are you sure you want to do this?\n' +
      'deleteRow=Delete Row\n' +
      'description=Description\n' +
      'device=Device\n' +
      'diagram=Diagram\n' +
      'diagramContent=Diagram Content\n' +
      'diagramLocked=Diagram has been locked to prevent further data loss.\n' +
      'diagramLockedBySince=The diagram is locked by {1} since {2} ago\n' +
      'diagramName=Diagram Name\n' +
      'diagramIsPublic=Diagram is public\n' +
      'diagramIsNotPublic=Diagram is not public\n' +
      'diamond=Diamond\n' +
      'diamondThin=Diamond (thin)\n' +
      'didYouKnow=Did you know...\n' +
      'direction=Direction\n' +
      'discard=Discard\n' +
      'discardChangesAndReconnect=Discard Changes and Reconnect\n' +
      'googleDriveMissingClickHere=Google Drive missing? Click here!\n' +
      'discardChanges=Discard Changes\n' +
      'disconnected=Disconnected\n' +
      'distribute=Distribute\n' +
      'done=Done\n' +
      'dotted=Dotted\n' +
      'doubleClickOrientation=Doubleclick to change orientation\n' +
      'doubleClickTooltip=Doubleclick to insert text\n' +
      'doubleClickChangeProperty=Doubleclick to change property name\n' +
      'download=Download\n' +
      'downloadDesktop=Download draw.io Desktop\n' +
      'downloadAs=Download as\n' +
      'clickHereToSave=Click here to save.\n' +
      'dpi=DPI\n' +
      'draftDiscarded=Draft discarded\n' +
      'draftSaved=Draft saved\n' +
      'dragElementsHere=Drag elements here\n' +
      'dragImagesHere=Drag images or URLs here\n' +
      'dragUrlsHere=Drag URLs here\n' +
      'draw.io=draw.io\n' +
      'drawing=Drawing{1}\n' +
      'drawingEmpty=Drawing is empty\n' +
      'drawingTooLarge=Drawing is too large\n' +
      'drawioForWork=Draw.io for GSuite\n' +
      'dropbox=Dropbox\n' +
      'duplicate=Duplicate\n' +
      'duplicateIt=Duplicate {1}\n' +
      'divider=Divider\n' +
      'dx=Dx\n' +
      'dy=Dy\n' +
      'east=East\n' +
      'edit=Edit\n' +
      'editData=Edit Data\n' +
      'editDiagram=Edit Diagram\n' +
      'editGeometry=Edit Geometry\n' +
      'editImage=Edit Image\n' +
      'editImageUrl=Edit Image URL\n' +
      'editLink=Edit Link\n' +
      'editShape=Edit Shape\n' +
      'editStyle=Edit Style\n' +
      'editText=Edit Text\n' +
      'editTooltip=Edit Tooltip\n' +
      'glass=Glass\n' +
      'googleImages=Google Images\n' +
      'imageSearch=Image Search\n' +
      'eip=EIP\n' +
      'embed=Embed\n' +
      'embedImages=Embed Images\n' +
      'mainEmbedNotice=Paste this into the page\n' +
      'electrical=Electrical\n' +
      'ellipse=Ellipse\n' +
      'embedNotice=Paste this once at the end of the page\n' +
      'enterGroup=Enter Group\n' +
      'enterName=Enter Name\n' +
      'enterPropertyName=Enter Property Name\n' +
      'enterValue=Enter Value\n' +
      'entityRelation=Entity Relation\n' +
      'error=Error\n' +
      'errorDeletingFile=Error deleting file\n' +
      'errorLoadingFile=Error loading file\n' +
      'errorRenamingFile=Error renaming file\n' +
      'errorRenamingFileNotFound=Error renaming file. File was not found.\n' +
      'errorRenamingFileForbidden=Error renaming file. Insufficient access rights.\n' +
      'errorSavingDraft=Error saving draft\n' +
      'errorSavingFile=Error saving file\n' +
      'errorSavingFileUnknown=Error authorizing with Google\'s servers. Please refresh the page to re-attempt.\n' +
      'errorSavingFileForbidden=Error saving file. Insufficient access rights.\n' +
      'errorSavingFileNameConflict=Could not save diagram. Current page already contains file named \'{1}\'.\n' +
      'errorSavingFileNotFound=Error saving file. File was not found.\n' +
      'errorSavingFileReadOnlyMode=Could not save diagram while read-only mode is active.\n' +
      'errorSavingFileSessionTimeout=Your session has ended. Please <a target=\'_blank\' href=\'{1}\'>{2}</a> and return to this tab to try to save again.\n' +
      'errorSendingFeedback=Error sending feedback.\n' +
      'errorUpdatingPreview=Error updating preview.\n' +
      'exit=Exit\n' +
      'exitGroup=Exit Group\n' +
      'expand=Expand\n' +
      'export=Export\n' +
      'exporting=Exporting\n' +
      'exportAs=Export as\n' +
      'exportOptionsDisabled=Export options disabled\n' +
      'exportOptionsDisabledDetails=The owner has disabled options to download, print or copy for commenters and viewers on this file.\n' +
      'externalChanges=External Changes\n' +
      'extras=Extras\n' +
      'facebook=Facebook\n' +
      'failedToSaveTryReconnect=Failed to save, trying to reconnect\n' +
      'featureRequest=Feature Request\n' +
      'feedback=Feedback\n' +
      'feedbackSent=Feedback successfully sent.\n' +
      'floorplans=Floorplans\n' +
      'file=File\n' +
      'fileChangedOverwriteDialog=The file has been modified. Do you want to save the file and overwrite those changes?\n' +
      'fileChangedSyncDialog=The file has been modified. Do you want to synchronize those changes?\n' +
      'fileChangedSync=The file has been modified. Click here to synchronize.\n' +
      'overwrite=Overwrite\n' +
      'synchronize=Synchronize\n' +
      'filename=Filename\n' +
      'fileExists=File already exists\n' +
      'fileNearlyFullSeeFaq=File nearly full, please see FAQ\n' +
      'fileNotFound=File not found\n' +
      'repositoryNotFound=Repository not found\n' +
      'fileNotFoundOrDenied=The file was not found. It does not exist or you do not have read access.\n' +
      'fileNotLoaded=File not loaded\n' +
      'fileNotSaved=File not saved\n' +
      'fileOpenLocation=How would you like to open these file(s)?\n' +
      'filetypeHtml=.html causes file to save as HTML with redirect to cloud URL\n' +
      'filetypePng=.png causes file to save as PNG with embedded data\n' +
      'filetypeSvg=.svg causes file to save as SVG with embedded data\n' +
      'fileWillBeSavedInAppFolder={1} will be saved in the app folder.\n' +
      'fill=Fill\n' +
      'fillColor=Fill Color\n' +
      'filterCards=Filter Cards\n' +
      'find=Find\n' +
      'fit=Fit\n' +
      'fitContainer=Resize Container\n' +
      'fitIntoContainer=Fit into Container\n' +
      'fitPage=Fit Page\n' +
      'fitPageWidth=Fit Page Width\n' +
      'fitTo=Fit to\n' +
      'fitToSheetsAcross=sheet(s) across\n' +
      'fitToBy=by\n' +
      'fitToSheetsDown=sheet(s) down\n' +
      'fitTwoPages=Two Pages\n' +
      'fitWindow=Fit Window\n' +
      'flip=Flip\n' +
      'flipH=Flip Horizontal\n' +
      'flipV=Flip Vertical\n' +
      'flowchart=Flowchart\n' +
      'folder=Folder\n' +
      'font=Font\n' +
      'fontColor=Font Color\n' +
      'fontFamily=Font Family\n' +
      'fontSize=Font Size\n' +
      'forbidden=You are not authorized to access this file\n' +
      'format=Format\n' +
      'formatPanel=Format Panel\n' +
      'formatted=Formatted\n' +
      'formattedText=Formatted Text\n' +
      'formatPng=PNG\n' +
      'formatGif=GIF\n' +
      'formatJpg=JPEG\n' +
      'formatPdf=PDF\n' +
      'formatSql=SQL\n' +
      'formatSvg=SVG\n' +
      'formatHtmlEmbedded=HTML\n' +
      'formatSvgEmbedded=SVG (with XML)\n' +
      'formatVsdx=VSDX\n' +
      'formatVssx=VSSX\n' +
      'formatXmlPlain=XML (Plain)\n' +
      'formatXml=XML\n' +
      'forum=Discussion/Help Forums\n' +
      'freehand=Freehand\n' +
      'fromTemplate=From Template\n' +
      'fromTemplateUrl=From Template URL\n' +
      'fromText=From Text\n' +
      'fromUrl=From URL\n' +
      'fromThisPage=From this page\n' +
      'fullscreen=Fullscreen\n' +
      'gap=Gap\n' +
      'gcp=GCP\n' +
      'general=General\n' +
      'github=GitHub\n' +
      'gitlab=GitLab\n' +
      'gliffy=Gliffy\n' +
      'global=Global\n' +
      'googleDocs=Google Docs\n' +
      'googleDrive=Google Drive\n' +
      'googleGadget=Google Gadget\n' +
      'googlePlus=Google+\n' +
      'googleSharingNotAvailable=Sharing is only available via Google Drive. Please click Open below and share from the more actions menu:\n' +
      'googleSlides=Google Slides\n' +
      'googleSites=Google Sites\n' +
      'googleSheets=Google Sheets\n' +
      'gradient=Gradient\n' +
      'gradientColor=Color\n' +
      'grid=Grid\n' +
      'gridColor=Grid Color\n' +
      'gridSize=Grid Size\n' +
      'group=Group\n' +
      'guides=Guides\n' +
      'hateApp=I hate draw.io\n' +
      'heading=Heading\n' +
      'height=Height\n' +
      'help=Help\n' +
      'helpTranslate=Help us translate this application\n' +
      'hide=Hide\n' +
      'hideIt=Hide {1}\n' +
      'hidden=Hidden\n' +
      'home=Home\n' +
      'horizontal=Horizontal\n' +
      'horizontalFlow=Horizontal Flow\n' +
      'horizontalTree=Horizontal Tree\n' +
      'howTranslate=How good is the translation in your language?\n' +
      'html=HTML\n' +
      'htmlText=HTML Text\n' +
      'id=ID\n' +
      'iframe=IFrame\n' +
      'ignore=Ignore\n' +
      'image=Image\n' +
      'imageUrl=Image URL\n' +
      'images=Images\n' +
      'imagePreviewError=This image couldn\'t be loaded for preview. Please check the URL.\n' +
      'imageTooBig=Image too big\n' +
      'imgur=Imgur\n' +
      'import=Import\n' +
      'importFrom=Import from\n' +
      'includeCopyOfMyDiagram=Include a copy of my diagram\n' +
      'increaseIndent=Increase Indent\n' +
      'decreaseIndent=Decrease Indent\n' +
      'insert=Insert\n' +
      'insertColumnBefore=Insert Column Left\n' +
      'insertColumnAfter=Insert Column Right\n' +
      'insertEllipse=Insert Ellipse\n' +
      'insertImage=Insert Image\n' +
      'insertHorizontalRule=Insert Horizontal Rule\n' +
      'insertLink=Insert Link\n' +
      'insertPage=Insert Page\n' +
      'insertRectangle=Insert Rectangle\n' +
      'insertRhombus=Insert Rhombus\n' +
      'insertRowBefore=Insert Row Above\n' +
      'insertRowAfter=Insert Row After\n' +
      'insertText=Insert Text\n' +
      'inserting=Inserting\n' +
      'invalidFilename=Diagram names must not contain the following characters: \ / | : ; { } < > & + ? = "\n' +
      'invalidLicenseSeeThisPage=Your license is invalid, please see this <a target="_blank" href="https://support.draw.io/display/DFCS/Licensing+your+draw.io+plugin">page</a>.\n' +
      'invalidInput=Invalid input\n' +
      'invalidName=Invalid name\n' +
      'invalidOrMissingFile=Invalid or missing file\n' +
      'invalidPublicUrl=Invalid public URL\n' +
      'isometric=Isometric\n' +
      'ios=iOS\n' +
      'italic=Italic\n' +
      'kennedy=Kennedy\n' +
      'keyboardShortcuts=Keyboard Shortcuts\n' +
      'layers=Layers\n' +
      'landscape=Landscape\n' +
      'language=Language\n' +
      'leanMapping=Lean Mapping\n' +
      'lastChange=Last change {1} ago\n' +
      'lessThanAMinute=less than a minute\n' +
      'licensingError=Licensing Error\n' +
      'licenseHasExpired=The license for {1} has expired on {2}. Click here.\n' +
      'licenseWillExpire=The license for {1} will expire on {2}. Click here.\n' +
      'lineJumps=Line jumps\n' +
      'linkAccountRequired=If the diagram is not public a Google account is required to view the link.\n' +
      'linkText=Link Text\n' +
      'list=List\n' +
      'minute=minute\n' +
      'minutes=minutes\n' +
      'hours=hours\n' +
      'days=days\n' +
      'months=months\n' +
      'years=years\n' +
      'restartForChangeRequired=Changes will take effect after page refresh.\n' +
      'laneColor=Lanecolor\n' +
      'lastModified=Last modified\n' +
      'layout=Layout\n' +
      'left=Left\n' +
      'leftAlign=Left Align\n' +
      'leftToRight=Left to right\n' +
      'libraryTooltip=Drag and drop shapes here or click + to insert. Double click to edit.\n' +
      'lightbox=Lightbox\n' +
      'line=Line\n' +
      'lineend=Line end\n' +
      'lineheight=Line Height\n' +
      'linestart=Line start\n' +
      'linewidth=Linewidth\n' +
      'link=Link\n' +
      'links=Links\n' +
      'loading=Loading\n' +
      'lockUnlock=Lock/Unlock\n' +
      'loggedOut=Logged Out\n' +
      'logIn=log in\n' +
      'loveIt=I love {1}\n' +
      'lucidchart=Lucidchart\n' +
      'maps=Maps\n' +
      'mathematicalTypesetting=Mathematical Typesetting\n' +
      'makeCopy=Make a Copy\n' +
      'manual=Manual\n' +
      'microsoftOffice=Microsoft Office\n' +
      'microsoftExcel=Microsoft Excel\n' +
      'microsoftPowerPoint=Microsoft PowerPoint\n' +
      'microsoftWord=Microsoft Word\n' +
      'middle=Middle\n' +
      'minimal=Minimal\n' +
      'misc=Misc\n' +
      'mockups=Mockups\n' +
      'modificationDate=Modification date\n' +
      'modifiedBy=Modified by\n' +
      'more=More\n' +
      'moreResults=More Results\n' +
      'moreShapes=More Shapes\n' +
      'move=Move\n' +
      'moveToFolder=Move to Folder\n' +
      'moving=Moving\n' +
      'moveSelectionTo=Move selection to {1}\n' +
      'name=Name\n' +
      'navigation=Navigation\n' +
      'network=Network\n' +
      'networking=Networking\n' +
      'new=New\n' +
      'newLibrary=New Library\n' +
      'nextPage=Next Page\n' +
      'no=No\n' +
      'noPickFolder=No, pick folder\n' +
      'noAttachments=No attachments found\n' +
      'noColor=No Color\n' +
      'noFiles=No Files\n' +
      'noFileSelected=No file selected\n' +
      'noLibraries=No libraries found\n' +
      'noMoreResults=No more results\n' +
      'none=None\n' +
      'noOtherViewers=No other viewers\n' +
      'noPlugins=No plugins\n' +
      'noPreview=No preview\n' +
      'noResponse=No response from server\n' +
      'noResultsFor=No results for \'{1}\'\n' +
      'noRevisions=No revisions\n' +
      'noSearchResults=No search results found\n' +
      'noPageContentOrNotSaved=No anchors found on this page or it hasn\'t been saved yet\n' +
      'normal=Normal\n' +
      'north=North\n' +
      'notADiagramFile=Not a diagram file\n' +
      'notALibraryFile=Not a library file\n' +
      'notAvailable=Not available\n' +
      'notAUtf8File=Not a UTF-8 file\n' +
      'notConnected=Not connected\n' +
      'note=Note\n' +
      'notUsingService=Not using {1}?\n' +
      'numberedList=Numbered list\n' +
      'offline=Offline\n' +
      'ok=OK\n' +
      'oneDrive=OneDrive\n' +
      'online=Online\n' +
      'opacity=Opacity\n' +
      'open=Open\n' +
      'openArrow=Open Arrow\n' +
      'openExistingDiagram=Open Existing Diagram\n' +
      'openFile=Open File\n' +
      'openFrom=Open from\n' +
      'openLibrary=Open Library\n' +
      'openLibraryFrom=Open Library from\n' +
      'openLink=Open Link\n' +
      'openInNewWindow=Open in New Window\n' +
      'openInThisWindow=Open in This Window\n' +
      'openIt=Open {1}\n' +
      'openRecent=Open Recent\n' +
      'openSupported=Supported formats are files saved from this software (.xml), .vsdx and .gliffy\n' +
      'options=Options\n' +
      'organic=Organic\n' +
      'orthogonal=Orthogonal\n' +
      'otherViewer=other viewer\n' +
      'otherViewers=other viewers\n' +
      'outline=Outline\n' +
      'oval=Oval\n' +
      'page=Page\n' +
      'pageContent=Page Content\n' +
      'pageNotFound=Page not found\n' +
      'pageWithNumber=Page-{1}\n' +
      'pages=Pages\n' +
      'pageView=Page View\n' +
      'pageSetup=Page Setup\n' +
      'pageScale=Page Scale\n' +
      'pan=Pan\n' +
      'panTooltip=Space+Drag to pan\n' +
      'paperSize=Paper Size\n' +
      'pattern=Pattern\n' +
      'paste=Paste\n' +
      'pasteHere=Paste here\n' +
      'pasteSize=Paste Size\n' +
      'pasteStyle=Paste Style\n' +
      'perimeter=Perimeter\n' +
      'permissionAnyone=Anyone can edit\n' +
      'permissionAuthor=Owner and admins can edit\n' +
      'pickFolder=Pick a folder\n' +
      'pickLibraryDialogTitle=Select Library\n' +
      'publicDiagramUrl=Public URL of the diagram\n' +
      'placeholders=Placeholders\n' +
      'plantUml=PlantUML\n' +
      'plugins=Plugins\n' +
      'pluginUrl=Plugin URL\n' +
      'pluginWarning=The page has requested to load the following plugin(s):\n \n {1}\n \n Would you like to load these plugin(s) now?\n \n NOTE : Only allow plugins to run if you fully understand the security implications of doing so.\n\n' +
      'plusTooltip=Click to connect and clone (ctrl+click to clone, shift+click to connect). Drag to connect (ctrl+drag to clone).\n' +
      'portrait=Portrait\n' +
      'position=Position\n' +
      'posterPrint=Poster Print\n' +
      'preferences=Preferences\n' +
      'preview=Preview\n' +
      'previousPage=Previous Page\n' +
      'print=Print\n' +
      'printAllPages=Print All Pages\n' +
      'procEng=Proc. Eng.\n' +
      'project=Project\n' +
      'priority=Priority\n' +
      'properties=Properties\n' +
      'publish=Publish\n' +
      'quickStart=Quick Start Video\n' +
      'rack=Rack\n' +
      'radialTree=Radial Tree\n' +
      'readOnly=Read-only\n' +
      'reconnecting=Reconnecting\n' +
      'recentlyUpdated=Recently Updated\n' +
      'recentlyViewed=Recently Viewed\n' +
      'rectangle=Rectangle\n' +
      'redirectToNewApp=This file was created or modified in a newer version of this app. You will be redirected now.\n' +
      'realtimeTimeout=It looks like you\'ve made a few changes while offline. We\'re sorry, these changes cannot be saved.\n' +
      'redo=Redo\n' +
      'refresh=Refresh\n' +
      'regularExpression=Regular Expression\n' +
      'relative=Relative\n' +
      'relativeUrlNotAllowed=Relative URL not allowed\n' +
      'rememberMe=Remember me\n' +
      'rememberThisSetting=Remember this setting\n' +
      'removeFormat=Clear Formatting\n' +
      'removeFromGroup=Remove from Group\n' +
      'removeIt=Remove {1}\n' +
      'removeWaypoint=Remove Waypoint\n' +
      'rename=Rename\n' +
      'renamed=Renamed\n' +
      'renameIt=Rename {1}\n' +
      'renaming=Renaming\n' +
      'replace=Replace\n' +
      'replaceIt={1} already exists. Do you want to replace it?\n' +
      'replaceExistingDrawing=Replace existing drawing\n' +
      'required=required\n' +
      'reset=Reset\n' +
      'resetView=Reset View\n' +
      'resize=Resize\n' +
      'resizeLargeImages=Do you want to resize large images to make the application run faster?\n' +
      'retina=Retina\n' +
      'responsive=Responsive\n' +
      'restore=Restore\n' +
      'restoring=Restoring\n' +
      'retryingIn=Retrying in {1} second(s)\n' +
      'retryingLoad=Load failed. Retrying...\n' +
      'retryingLogin=Login time out. Retrying...\n' +
      'reverse=Reverse\n' +
      'revision=Revision\n' +
      'revisionHistory=Revision History\n' +
      'rhombus=Rhombus\n' +
      'right=Right\n' +
      'rightAlign=Right Align\n' +
      'rightToLeft=Right to left\n' +
      'rotate=Rotate\n' +
      'rotateTooltip=Click and drag to rotate, click to turn shape only by 90 degrees\n' +
      'rotation=Rotation\n' +
      'rounded=Rounded\n' +
      'save=Save\n' +
      'saveAndExit=Save & Exit\n' +
      'saveAs=Save as\n' +
      'saveAsXmlFile=Save as XML file?\n' +
      'saved=Saved\n' +
      'saveDiagramFirst=Please save the diagram first\n' +
      'saveDiagramsTo=Save diagrams to\n' +
      'saveLibrary403=Insufficient permissions to edit this library\n' +
      'saveLibrary500=There was an error while saving the library\n' +
      'saving=Saving\n' +
      'scratchpad=Scratchpad\n' +
      'scrollbars=Scrollbars\n' +
      'search=Search\n' +
      'searchShapes=Search Shapes\n' +
      'selectAll=Select All\n' +
      'selectionOnly=Selection Only\n' +
      'selectCard=Select Card\n' +
      'selectEdges=Select Edges\n' +
      'selectFile=Select File\n' +
      'selectFolder=Select Folder\n' +
      'selectFont=Select Font\n' +
      'selectNone=Select None\n' +
      'selectTemplate=Select Template\n' +
      'selectVertices=Select Vertices\n' +
      'sendMessage=Send\n' +
      'sendYourFeedbackToDrawIo=Send your feedback to draw.io\n' +
      'serviceUnavailableOrBlocked=Service unavailable or blocked\n' +
      'sessionExpired=Your session has expired. Please refresh the browser window.\n' +
      'sessionTimeoutOnSave=Your session has timed out and you have been disconnected from the Google Drive. Press OK to login and save. \n' +
      'setAsDefaultStyle=Set as Default Style\n' +
      'shadow=Shadow\n' +
      'shape=Shape\n' +
      'shapes=Shapes\n' +
      'share=Share\n' +
      'shareLink=Link for shared editing\n' +
      'sharp=Sharp\n' +
      'show=Show\n' +
      'showStartScreen=Show Start Screen\n' +
      'sidebarTooltip=Click to expand. Drag and drop shapes into the diagram. Shift+click to change selection. Alt+click to insert and connect.\n' +
      'signs=Signs\n' +
      'signOut=Sign out\n' +
      'simple=Simple\n' +
      'simpleArrow=Simple Arrow\n' +
      'simpleViewer=Simple Viewer\n' +
      'size=Size\n' +
      'solid=Solid\n' +
      'sourceSpacing=Source Spacing\n' +
      'south=South\n' +
      'software=Software\n' +
      'space=Space\n' +
      'spacing=Spacing\n' +
      'specialLink=Special Link\n' +
      'standard=Standard\n' +
      'startDrawing=Start drawing\n' +
      'stopDrawing=Stop drawing\n' +
      'starting=Starting\n' +
      'straight=Straight\n' +
      'strikethrough=Strikethrough\n' +
      'strokeColor=Line Color\n' +
      'style=Style\n' +
      'subscript=Subscript\n' +
      'summary=Summary\n' +
      'superscript=Superscript\n' +
      'support=Support\n' +
      'sysml=SysML\n' +
      'tags=Tags\n' +
      'table=Table\n' +
      'tables=Tables\n' +
      'takeOver=Take Over\n' +
      'targetSpacing=Target Spacing\n' +
      'template=Template\n' +
      'templates=Templates\n' +
      'text=Text\n' +
      'textAlignment=Text Alignment\n' +
      'textOpacity=Text Opacity\n' +
      'theme=Theme\n' +
      'timeout=Timeout\n' +
      'title=Title\n' +
      'to=to\n' +
      'toBack=To Back\n' +
      'toFront=To Front\n' +
      'toolbar=Toolbar\n' +
      'tooltips=Tooltips\n' +
      'top=Top\n' +
      'topAlign=Top Align\n' +
      'topLeft=Top Left\n' +
      'topRight=Top Right\n' +
      'transparent=Transparent\n' +
      'transparentBackground=Transparent Background\n' +
      'trello=Trello\n' +
      'tryAgain=Try again\n' +
      'tryOpeningViaThisPage=Try opening via this page\n' +
      'turn=Rotate shape only by 90°\n' +
      'type=Type\n' +
      'twitter=Twitter\n' +
      'uml=UML\n' +
      'underline=Underline\n' +
      'undo=Undo\n' +
      'ungroup=Ungroup\n' +
      'unsavedChanges=Unsaved changes\n' +
      'unsavedChangesClickHereToSave=Unsaved changes. Click here to save.\n' +
      'untitled=Untitled\n' +
      'untitledDiagram=Untitled Diagram\n' +
      'untitledLayer=Untitled Layer\n' +
      'untitledLibrary=Untitled Library\n' +
      'unknownError=Unknown error\n' +
      'updateFile=Update {1}\n' +
      'updatingDocument=Updating Document. Please wait...\n' +
      'updatingPreview=Updating Preview. Please wait...\n' +
      'updatingSelection=Updating Selection. Please wait...\n' +
      'upload=Upload\n' +
      'url=URL\n' +
      'useOffline=Use Offline\n' +
      'useRootFolder=Use root folder?\n' +
      'userManual=User Manual\n' +
      'vertical=Vertical\n' +
      'verticalFlow=Vertical Flow\n' +
      'verticalTree=Vertical Tree\n' +
      'view=View\n' +
      'viewerSettings=Viewer Settings\n' +
      'viewUrl=Link to view: {1}\n' +
      'voiceAssistant=Voice Assistant (beta)\n' +
      'warning=Warning\n' +
      'waypoints=Waypoints\n' +
      'west=West\n' +
      'width=Width\n' +
      'wiki=Wiki\n' +
      'wordWrap=Word Wrap\n' +
      'writingDirection=Writing Direction\n' +
      'yes=Yes\n' +
      'yourEmailAddress=Your email address\n' +
      'zoom=Zoom\n' +
      'zoomIn=Zoom In\n' +
      'zoomOut=Zoom Out\n' +
      'basic=Basic\n' +
      'businessprocess=Business Processes\n' +
      'charts=Charts\n' +
      'engineering=Engineering\n' +
      'flowcharts=Flowcharts\n' +
      'gmdl=Material Design\n' +
      'mindmaps=Mindmaps\n' +
      'mockups=Mockups\n' +
      'networkdiagrams=Network Diagrams\n' +
      'nothingIsSelected=Nothing is selected\n' +
      'other=Other\n' +
      'softwaredesign=Software Design\n' +
      'venndiagrams=Venn Diagrams\n' +
      'webEmailOrOther=Web, email or any other internet address\n' +
      'webLink=Web Link\n' +
      'wireframes=Wireframes\n' +
      'property=Property\n' +
      'value=Value\n' +
      'showMore=Show More\n' +
      'showLess=Show Less\n' +
      'myDiagrams=My Diagrams\n' +
      'allDiagrams=All Diagrams\n' +
      'recentlyUsed=Recently used\n' +
      'listView=List view\n' +
      'gridView=Grid view\n' +
      'resultsFor=Results for \'{1}\'\n' +
      'oneDriveCharsNotAllowed=The following characters are not allowed: ~ " # %  * : < > ? / \ { | }\n' +
      'oneDriveInvalidDeviceName=The specified device name is invalid\n' +
      'officeNotLoggedOD=You are not logged in to OneDrive. Please open draw.io task pane and login first.\n' +
      'officeSelectSingleDiag=Please select a single draw.io diagram only without other contents.\n' +
      'officeSelectDiag=Please select a draw.io diagram.\n' +
      'officeCannotFindDiagram=Cannot find a draw.io diagram in the selection\n' +
      'noDiagrams=No diagrams found\n' +
      'authFailed=Authentication failed\n' +
      'officeFailedAuthMsg=Unable to successfully authenticate user or authorize application.\n' +
      'convertingDiagramFailed=Converting diagram failed\n' +
      'officeCopyImgErrMsg=Due to some limitations in the host application, the image could not be inserted. Please manually copy the image then paste it to the document.\n' +
      'insertingImageFailed=Inserting image failed\n' +
      'officeCopyImgInst=Instructions: Right-click the image below. Select "Copy image" from the context menu. Then, in the document, right-click and select "Paste" from the context menu.\n' +
      'folderEmpty=Folder is empty\n' +
      'recent=Recent\n' +
      'sharedWithMe=Shared With Me\n' +
      'sharepointSites=Sharepoint Sites\n' +
      'errorFetchingFolder=Error fetching folder items\n' +
      'errorAuthOD=Error authenticating to OneDrive\n' +
      'officeMainHeader=Adds draw.io diagrams to your document.\n' +
      'officeStepsHeader=This add-in performs the following steps:\n' +
      'officeStep1=Connects to Microsoft OneDrive, Google Drive or your device.\n' +
      'officeStep2=Select a draw.io diagram.\n' +
      'officeStep3=Insert the diagram into the document.\n' +
      'officeAuthPopupInfo=Please complete the authentication in the pop-up window.\n' +
      'officeSelDiag=Select draw.io Diagram:\n' +
      'files=Files\n' +
      'shared=Shared\n' +
      'sharepoint=Sharepoint\n' +
      'officeManualUpdateInst=Instructions: Copy draw.io diagram from the document. Then, in the box below, right-click and select "Paste" from the context menu.\n' +
      'officeClickToEdit=Click icon to start editing:\n' +
      'pasteDiagram=Paste draw.io diagram here\n' +
      'connectOD=Connect to OneDrive\n' +
      'selectChildren=Select Children\n' +
      'selectSiblings=Select Siblings\n' +
      'selectParent=Select Parent\n' +
      'selectDescendants=Select Descendants\n' +
      'lastSaved=Last saved {1} ago\n' +
      'resolve=Resolve\n' +
      'reopen=Re-open\n' +
      'showResolved=Show Resolved\n' +
      'reply=Reply\n' +
      'objectNotFound=Object not found\n' +
      'reOpened=Re-opened\n' +
      'markedAsResolved=Marked as resolved\n' +
      'noCommentsFound=No comments found\n' +
      'comments=Comments\n' +
      'timeAgo={1} ago\n' +
      'confluenceCloud=Confluence Cloud\n' +
      'libraries=Libraries\n' +
      'confAnchor=Confluence Page Anchor\n' +
      'confTimeout=The connection has timed out\n' +
      'confSrvTakeTooLong=The server at {1} is taking too long to respond.\n' +
      'confCannotInsertNew=Cannot insert draw.io diagram to a new Confluence page\n' +
      'confSaveTry=Please save the page and try again.\n' +
      'confCannotGetID=Unable to determine page ID\n' +
      'confContactAdmin=Please contact your Confluence administrator.\n' +
      'readErr=Read Error\n' +
      'editingErr=Editing Error\n' +
      'confExtEditNotPossible=This diagram cannot be edited externally. Please try editing it while editing the page\n' +
      'confEditedExt=Diagram/Page edited externally\n' +
      'diagNotFound=Diagram Not Found\n' +
      'confEditedExtRefresh=Diagram/Page is edited externally. Please refresh the page.\n' +
      'confCannotEditDraftDelOrExt=Cannot edit diagrams in a draft page, diagram is deleted from the page, or diagram is edited externally. Please, check the page.\n' +
      'retBack=Return back\n' +
      'confDiagNotPublished=The diagram does not belong to a published page\n' +
      'createdByDraw=Created by draw.io\n' +
      'filenameShort=Filename too short\n' +
      'invalidChars=Invalid characters\n' +
      'alreadyExst={1} already exists\n' +
      'draftReadErr=Draft Read Error\n' +
      'diagCantLoad=Diagram cannot be loaded\n' +
      'draftWriteErr=Draft Write Error\n' +
      'draftCantCreate=Draft could not be created\n' +
      'confDuplName=Duplicate diagram name detected. Please pick another name.\n' +
      'confSessionExpired=Looks like your session expired. Log in again to keep working.\n' +
      'login=Login\n' +
      'drawPrev=draw.io preview\n' +
      'drwaDiag=draw.io diagram\n' +
      'unknownErr=Unkown Error\n' +
      'invalidCallFnNotFound=Invalid Call: {1} not found\n' +
      'invalidCallErrOccured=Invalid Call: An error occured, {1}\n' +
      'anonymous=Anonymous\n' +
      'confGotoPage=Go to containing page\n' +
      'showComments=Show Comments\n' +
      'confError=Error: {1}\n' +
      'gliffyImport=Gliffy Import\n' +
      'gliffyImportInst1=Click the "Start Import" button to import all Gliffy diagrams to draw.io.\n' +
      'gliffyImportInst2=Please note that the import procedure will take some time and the browser window must remain open until the import is completed.\n' +
      'startImport=Start Import\n' +
      'drawConfig=draw.io Configuration\n' +
      'customLib=Custom Libraries\n' +
      'customTemp=Custom Templates\n' +
      'pageIdsExp=Page IDs Export\n' +
      'drawReindex=draw.io re-indexing (beta)\n' +
      'working=Working\n' +
      'drawConfigNotFoundInst=draw.io Configuration Space (DRAWIOCONFIG) does not exist. This space is needed to store draw.io configuration files and custom libraries/templates.\n' +
      'createConfSp=Create Config Space\n' +
      'unexpErrRefresh=Unexpected error, please refresh the page and try again.\n' +
      'configJSONInst=Write draw.io JSON configuration in the editor below then click save. If you need help, please refer to\n' +
      'thisPage=this page\n' +
      'curCustLib=Current Custom Libraries\n' +
      'libName=Library Name\n' +
      'action=Action\n' +
      'drawConfID=draw.io Config ID\n' +
      'addLibInst=Click the "Add Library" button to upload a new library.\n' +
      'addLib=Add Library\n' +
      'customTempInst1=Custom templates are draw.io diagrams saved in children pages of\n' +
      'customTempInst2=For more details, please refer to\n' +
      'tempsPage=Templates page\n' +
      'pageIdsExpInst1=Click the "Start Export" button to export all pages IDs.\n' +
      'pageIdsExpInst2=Please note that the export procedure will take some time and the browser window must remain open until the export is completed.\n' +
      'startExp=Start Export\n' +
      'refreshDrawIndex=Refresh draw.io Diagrams Index\n' +
      'reindexInst1=Click the "Start Indexing" button to refresh draw.io diagrams index.\n' +
      'reindexInst2=Please note that the indexing procedure will take some time and the browser window must remain open until the indexing is completed.\n' +
      'startIndexing=Start Indexing\n' +
      'confAPageFoundFetch=Page "{1}" found. Fetching\n' +
      'confAAllDiagDone=All {1} diagrams processed. Process finished.\n' +
      'confAStartedProcessing=Started processing page "{1}"\n' +
      'confAAllDiagInPageDone=All {1} diagrams in page "{2}" processed successfully.\n' +
      'confAPartialDiagDone={1} out of {2} {3} diagrams in page "{4}" processed successfully.\n' +
      'confAUpdatePageFailed=Updating page "{1}" failed.\n' +
      'confANoDiagFoundInPage=No {1} diagrams found in page "{2}".\n' +
      'confAFetchPageFailed=Fetching the page failed.\n' +
      'confANoDiagFound=No {1} diagrams found. Process finished.\n' +
      'confASearchFailed=Searching for {1} diagrams failed. Please try again later.\n' +
      'confAGliffyDiagFound=Gliffy diagram "{1}" found. Importing\n' +
      'confAGliffyDiagImported=Gliffy diagram "{1}" imported successfully.\n' +
      'confASavingImpGliffyFailed=Saving imported Gliffy diagram "{1}" failed.\n' +
      'confAImportedFromByDraw=Imported from "{1}" by draw.io\n' +
      'confAImportGliffyFailed=Importing Gliffy diagram "{1}" failed.\n' +
      'confAFetchGliffyFailed=Fetching Gliffy diagram "{1}" failed.\n' +
      'confACheckBrokenDiagLnk=Checking for broken diagrams links.\n' +
      'confADelDiagLinkOf=Deleting diagram link of "{1}"\n' +
      'confADupLnk=(duplicate link)\n' +
      'confADelDiagLnkFailed=Deleting diagram link of "{1}" failed.\n' +
      'confAUnexpErrProcessPage=Unexpected error during processing the page with id: {1}\n' +
      'confADiagFoundIndex=Diagram "{1}" found. Indexing\n' +
      'confADiagIndexSucc=Diagram "{1}" indexed successfully.\n' +
      'confAIndexDiagFailed=Indexing diagram "{1}" failed.\n' +
      'confASkipDiagOtherPage=Skipped "{1}" as it belongs to another page!\n' +
      'confADiagUptoDate=Diagram "{1}" is up to date.\n' +
      'confACheckPagesWDraw=Checking pages having draw.io diagrams.\n' +
      'confAErrOccured=An error occured!\n' +
      'savedSucc=Saved successfully\n' +
      'confASaveFailedErr=Saving Failed (Unexpected Error)\n' +
      'character=Character\n' +
      'confAConfPageDesc=This page contains draw.io configuration file (configuration.json) as attachment\n' +
      'confALibPageDesc=This page contains draw.io custom libraries as attachments\n' +
      'confATempPageDesc=This page contains draw.io custom templates as attachments\n' +
      'working=Working\n' +
      'confAConfSpaceDesc=This space is used to store draw.io configuration files and custom libraries/templates\n' +
      'confANoCustLib=No Custom Libraries\n' +
      'delFailed=Delete failed!\n' +
      'showID=Show ID\n' +
      'confAIncorrectLibFileType=Incorrect file type. Libraries should be XML files.\n' +
      'uploading=Uploading\n' +
      'confALibExist=This library already exists\n' +
      'confAUploadSucc=Uploaded successfully\n' +
      'confAUploadFailErr=Upload Failed (Unexpected Error)\n' +
      'hiResPreview=High Res Preview\n' +
      'officeNotLoggedGD=You are not logged in to Google Drive. Please open draw.io task pane and login first.\n' +
      'officePopupInfo=Please complete the process in the pop-up window.\n' +
      'pickODFile=Pick OneDrive File\n' +
      'pickGDriveFile=Pick Google Drive File\n' +
      'pickDeviceFile=Pick Device File\n' +
      'vsdNoConfig="vsdurl" is not configured\n' +
      'ruler=Ruler\n' +
      'units=Units\n' +
      'points=Points\n' +
      'inches=Inches\n' +
      'millimeters=Millimeters'
    );
  };
})();